Update Riders frontend
cornell-dti/carriage-web pull request #122
Opened 2021-03-01 22:25 UTC by pihucode

### Summary
This PR updates the frontend design for the Riders tabs with the designs on Figma.

- [x] Update Sidebar icons with new icons.
- [x] Modify Riders table to match the columns specified in the Figma design.

### Test Plan
Compare frontend site with the designs on Figma.
![image](https://user-images.githubusercontent.com/48143149/110878971-27e06280-82aa-11eb-8b23-c1696fc246d9.png)

2021-03-01 22:28 UTC, mg2239 reviewed
oh sorry for not being clear, dispatchers are admin so you can use `/api/dispatchers` to get all the admin data

2021-03-01 22:34 UTC, pihucode commented
> oh sorry for not being clear, dispatchers are admin so you can use `/api/dispatchers` to get all the admin data

Ah I see! The Admin card designs on Figma have availability and car information but the dispatcher schema doesn't have either so do I leave those out?

2021-03-01 22:56 UTC, mg2239 commented
> Ah I see! The Admin card designs on Figma have availability and car information but the dispatcher schema doesn't have either so do I leave those out?

good question, im actually checking with nina and bryan about what the user types are and what info is stored. turns out some admin can be drivers, so we might have to wait on this PR for a little

2021-03-06 02:53 UTC, mg2239 approved these changes
table looks good! i noticed that the sidebar, title of the page, and modal button still say rider, so they should be changed to student to match the designs. 

also if possible, could you fix how the disability column is displayed? the current rider type doesn't look up to date with the current schema, so updating it might break some other things, but you could define a `newRider` type for now, and ill go in after this PR merges to do the full fix.

2021-03-06 02:53 UTC, mg2239 commented on frontend/src/components/TableComponents/TableCell.tsx
> +      {netId}
the first cell of a table isn't necessarily always going to be a name + netid, i think if you change the type of `data` to be ReactNode you can pass in JSX or strings

2021-03-06 02:53 UTC, mg2239 requested changes
oops meant to request changes instead

2021-03-11 21:46 UTC, mg2239 requested changes

2021-03-11 21:46 UTC, mg2239 commented on frontend/src/components/TableComponents/TableCell.tsx
> -  ButtonModal?: () => JSX.Element;
the button handler is needed for other tables, just not the riders table. also we need the first + last fields for the riders table or else the table cells won't be styled properly

2021-03-11 21:46 UTC, mg2239 commented on frontend/src/components/TableComponents/TableCell.tsx
> -  } if (tag) {
add this code back in

2021-03-11 21:46 UTC, mg2239 commented on frontend/src/components/TableComponents/TableRow.tsx
> -          ButtonModal={ButtonModal}
add this code back in

2021-03-11 21:46 UTC, mg2239 commented on frontend/src/components/TableComponents/TableRow.tsx
> -        last={false}
add this code back

2021-03-11 21:49 UTC, mg2239 reviewed
thanks for the changes! since the table components are shared with every table in the frontend, only delete things if they are not used for any other table. other than that everything looks good to me

2021-03-13 21:13 UTC, mg2239 approved these changes

2021-03-14 21:48 UTC, merged