Export scheduled rides into CSV
cornell-dti/carriage-web pull request #126
Opened 2021-03-05 04:04 UTC by Becky-Hu-82

### Summary 

This pull request enables the export of unscheduled rides into csv files by

- using fast-csv to convert today's rides into readable stream,
- using react-csv to download the data 

### Test Plan 

Go to /home/export and click the export button in the bottom, see if the data can correctly output into a csv file.

### Notes 

Right now there is an error message saying `id not found in Rides`, which is something we need to fix.

### Breaking Changes  

<!-- - Database schema change (anything that changes DynamoDB document structure)
<!-- - Other change that could cause problems (Detailed in notes)

2021-03-11 17:57 UTC, mg2239 requested changes
code works well, just a few comments:
![image](https://user-images.githubusercontent.com/20343975/110831643-6ead6880-8268-11eb-9fcf-cdd70e4e59e7.png)
you'll want to process this data more before sending it from the server (i.e remove id, late, status, etc. and make the dates, driver, rider, etc. more readable). remember to look at the spreadsheet i sent for what is needed

also something i didn't notice before is that the export preview page and this request are returning unscheduled rides, but we only want scheduled and past rides

and maybe check with jahin if the download button is okay being at the bottom of the page? there doesn't seem to be a design for where it should be but would be good to double check

2021-03-11 17:57 UTC, mg2239 requested changes

2021-03-11 17:57 UTC, mg2239 commented on frontend/src/components/ExportPreview/ExportPreview.tsx
> +         filename='scheduledRides.csv'
include the date in the filename too

2021-03-13 20:42 UTC, mg2239 commented
fixed some issues i was having with the exporting so it should be working now, only thing is that when exporting on a day with no scheduled rides, this is what shows up
![image](https://user-images.githubusercontent.com/20343975/111043811-ab1cc800-8412-11eb-9e71-10b6a744bb3d.png)
could you figure out how to either make this a blank csv, or have just the column headers but no data?

2021-03-15 05:41 UTC, Becky-Hu-82 commented
> fixed some issues i was having with the exporting so it should be working now, only thing is that when exporting on a day with no scheduled rides, this is what shows up
> ![image](https://user-images.githubusercontent.com/20343975/111043811-ab1cc800-8412-11eb-9e71-10b6a744bb3d.png)
> could you figure out how to either make this a blank csv, or have just the column headers but no data?

just made some changes to solve this problem, but I can still only test the data in postman so don't know if it works

2021-03-15 15:44 UTC, mg2239 approved these changes
yep works on my end 👍

2021-03-15 15:50 UTC, merged