implemented toast notifications for Rider and EmployeeModal
cornell-dti/carriage-web pull request #167
Opened 2021-04-07 22:37 UTC by aaronkang7

### Summary 

This pull request implements toast notifications for rider and employee modals. There seems to be a problem with +Add Ride submission, but if that is fixed, the toast should work as well. The add Location form doesn't seem to have a separate modal yet so I didn't integrate the toast notification to it just yet.  

Toast notifications are automatically dismissed after 4 seconds after form submision.

This pull request is the first step towards implementing feature Foo

- [x] implemented X
- [ ] fixed Y

### Test Plan 

### Notes 

### Breaking Changes  

<!-- - Database schema change (anything that changes DynamoDB document structure)
<!-- - Other change that could cause problems (Detailed in notes)

2021-04-07 23:26 UTC, mg2239 commented on frontend/src/components/EmployeeModal/EmployeeModal.tsx
> +      {showingToast ? showToast('The employee has been added.') : null}
you can just use the component itself here

2021-04-07 23:27 UTC, mg2239 commented on frontend/src/components/EmployeeModal/EmployeeModal.tsx
> +    setToast(true);
we dont want this to show if they close out before submitting, only when a submission is successful

2021-04-11 03:30 UTC, mg2239 requested changes
made a few small changes cause i thought it was good to go, but noticed on the designs that the toast also shows up when the schedule is downloaded. could you add that in too?

2021-04-11 03:54 UTC, aaronkang7 commented
> made a few small changes cause i thought it was good to go, but noticed on the designs that the toast also shows up when the schedule is downloaded. could you add that in too?

2021-04-11 04:25 UTC, mg2239 requested changes
can you use the download icon too

2021-04-11 04:26 UTC, mg2239 approved these changes
oops i was looking at the wrong design, nvm looks good lol

2021-04-11 04:41 UTC, aaronkang7 commented
> oops i was looking at the wrong design, nvm looks good lol

oh, I'll just delete the commit then!

2021-04-20 01:10 UTC, merged