added mobile support to backend
cornell-dti/carriage-web pull request #174
Opened 2021-04-12 00:10 UTC by mly32

### Summary 

Updated admin's `subscribeUser` and the router for notifications.

The changed endpoints:

- `/subscribe` expects
  ```
  platform: string ("web", "android", "ios driver", or "ios rider") 
  token?: string (only for mobile)
  webSub?: object (only for web)
  ``` 
  where `webSub` is the same as the prior code (endpoint and keys arguments)

- `/sendAll` expects
  ```
  {
    "msg": "foo bar"
  }
  ```

### Test Plan 

Rerun the same admin tests as last time. No testing was done for mobile yet. 

If mobile testing is done, set the platform to `android` regardless of the device's physical platform.

### Notes 

### Breaking Changes  

updated `.env` files

<!-- - Database schema change (anything that changes DynamoDB document structure)
<!-- - Other change that could cause problems (Detailed in notes)

2021-04-14 20:14 UTC, mg2239 requested changes

2021-04-14 20:14 UTC, mg2239 commented on server/router/notification.ts
> +  const arn = plat === 'android' ? snsValues.android : ios;
may want to add checks if plat is not a valid platform

2021-04-14 20:15 UTC, mg2239 commented on server/router/notification.ts
> +    : { platform: req.body.platform, token: req.body.token };
same checks here

2021-04-19 23:55 UTC, mg2239 requested changes

2021-04-22 22:54 UTC, mly32 commented on server/router/notification.ts
> +  const arn = plat === 'android' ? snsValues.android : ios;
it doesn't because the function calling subscribe does the check (line 133).

2021-04-22 23:06 UTC, mg2239 commented on server/router/notification.ts
> +  const arn = plat === 'android' ? snsValues.android : ios;
oops my bad

2021-04-22 23:06 UTC, mg2239 approved these changes

2021-04-23 01:35 UTC, merged