Date filters on the analytics page
cornell-dti/carriage-web pull request #204
Opened 2021-04-28 04:14 UTC by Becky-Hu-82

### Summary 

This pull request implements the date filters on the analytics page.

- implemented a month picker and a year picker
- implemented a date range picker
![image](https://user-images.githubusercontent.com/60638132/116345739-be170c00-a7b6-11eb-8f38-dfbe4e0e93f9.png)

2021-04-28 22:50 UTC, mg2239 requested changes
can you better align these to the figma styles?

2021-05-09 23:44 UTC, Becky-Hu-82 commented
> I was wondering if you can use the icons (i.e. the calendar icon) provided in the Figma to customize the date-picker? (I can't run this on my end at the moment because of some error). But other than that it looks great to me!

That's a good point! Just changed the icon!

2021-05-10 00:33 UTC, mg2239 requested changes
![image](https://user-images.githubusercontent.com/20343975/117592139-850b5f80-b105-11eb-90bd-1c72f1abe9b6.png)
im getting a dependency error with react-dropdown-date and our version of react. can you also try reinstalling dependencies and see? if its also happening on your end, would it be possible to use native html inputs instead?

2021-05-12 21:50 UTC, mg2239 requested changes
overall looks good, but just a few changes to better separate the component logic

2021-05-12 21:50 UTC, mg2239 commented on frontend/src/components/AnalyticsTable/AnalyticsTable.tsx
> +
this logic should be in the analytics overview component, not in the table component

2021-05-12 21:50 UTC, mg2239 commented on frontend/src/components/AnalyticsTable/AnalyticsTable.tsx
> +    <AnalyticsOverview stats={generateStatsArr()} />
move these to the analytics page in Admin. when connecting to backend, the analytics page will handle getting stats and passing the table data to all components, including the table and analytics overview

2021-05-24 01:29 UTC, mg2239 approved these changes
swapped out inputs to just be native, other changes require a lot of refactoring so that can be handled in a separate PR

2021-05-24 01:30 UTC, merged