Detail links
cornell-dti/carriage-web pull request #212
Opened 2021-05-04 17:41 UTC by zack-ashen

### Summary 

Make it possible to visit student detail and rider detail pages directly via link. 

### Test Plan 

Difficult to demo this feature...

2021-05-09 23:26 UTC, mg2239 requested changes
works great, just a couple small changes 👍

2021-05-09 23:26 UTC, mg2239 commented on frontend/src/components/EmployeeCards/EmployeeCards.tsx
> +    <Link to={{ pathname: '/employees/employee/' + userInfo.id, state: userInfo }}
you can make the pathname /admins or /drivers depending on the user, that way you wont have to make two requests later on in EmployeeDetail. just be sure to change the routes accordingly too

2021-05-09 23:26 UTC, mg2239 commented on frontend/src/components/UserTables/StudentsTable.tsx
> +          pathname: '/riders/rider/' + r.id,
this can also just be /riders/ + r.id

2021-05-10 02:13 UTC, zack-ashen reviewed
I think I made the changes you requested...

2021-05-12 22:21 UTC, mg2239 approved these changes
looks good, i did the route changes i was suggesting (basically making the route /admin/admins, /admin/drivers, or /admin/riders so you can easily identify the user type) and changed the routing accordingly

2021-05-14 02:14 UTC, merged