[WIP] Upcoming and Past Rides Table for Rider Web
cornell-dti/carriage-web pull request #221
Opened 2021-05-10 15:41 UTC by pihucode

### Summary 
This PR implements the upcoming and past rides tables for Rider Web.
- [ ] Waiting on designers to approve current design

### Test Plan 
If your rider account does not have rides, replace `id` in `RiderHome` with a hardcoded rider id such as `'e4586b99-5dce-47ac-b27d-0fbb3f8b4389'`

![image](https://user-images.githubusercontent.com/48143149/117685137-a27f0e80-b183-11eb-8db3-f90d3abed8db.png)

![image](https://user-images.githubusercontent.com/48143149/117685157-a743c280-b183-11eb-9c87-4dcc4de2bb0d.png)

### Breaking Changes  
The `Ride` type has been changed to include new fields.
```
type Ride = {
  id: string;
  type: string;
  status: string;
  late?: boolean;
  startLocation: Location;
  endLocation: Location;
  startTime: string;
  endTime: string;
  rider: Rider;
  driver?: Driver;
  recurring: boolean;
  recurringDays?: number[];
  endDate?: string;
  deleted?: boolean;
  edits?: string[];
};
```

2021-05-12 22:33 UTC, mg2239 requested changes
have yet to look through all of this PR, but it seems like no future repeating instances of a ride are being displayed in the scheduled table. we need this in case a rider needs to edit a repeating instance of a ride. 

to create the future instances, we just need the frontend to generate fake ride rows on each `recurringDay` the ride occurs on until `endDate`. all dates in `deleted` are days the ride should not be shown on. helen has implemented this for rider mobile, so feel free to ask her or me if you need any clarification on how to do that

2021-05-12 22:33 UTC, mg2239 commented on frontend/src/components/UserTables/RiderRidesTable.tsx
> +          };
you can use moment().format() for this

2021-05-12 22:35 UTC, mg2239 commented on frontend/src/types/index.ts
> +  deleted?: boolean;
oops i think the API docs might not be up to date, we changed `deleted` to be an array of string dates

2021-05-22 04:04 UTC, mg2239 approved these changes
updated from master to make sure things worked correctly, and fixed some issues with filtering and sorting and responsive design. overall very nice work! just curious why the design in the figma wasn't used, since it seems doable to me. but rn it seems like it might take too much time to redo, so it should be good for now.

2021-05-22 23:14 UTC, pihucode commented
> updated from master to make sure things worked correctly, and fixed some issues with filtering and sorting, responsive design, and accessibility. overall very nice work! just curious why the design in the figma wasn't used, since it seems doable to me. but rn it seems like it might take too much time to redo, so it should be good for now.

Thank you for the fixes! I talked with the designers and apparently the design on Figma is outdated so the implemented design is the desired one (includes a time column, groups rides by date, no background color for the repeating dates column).

2021-05-22 23:15 UTC, merged