updated schedule view with correct colors and arrows
cornell-dti/carriage-web pull request #233
Opened 2021-05-23 14:37 UTC by mly32

### Summary 

- Fixed schedule rides so it uses a color map. It is currently based on the driver id (colors may need to be updated if designs have changed since last semester).
- Changed view more state to also use buttons (8hr range).

![image](https://user-images.githubusercontent.com/52215742/119264619-f04b3c00-bbb1-11eb-92db-0f33e36c4d85.png)
Here, the rides for a driver are given yellow.

### Test Plan 

Add scheduled rides and check colors + time ranges (arrows should be disabled when they are no longer allowed).

### Notes 

On the Figma designs, the rides have colors that are not based on driver id, but I am not sure how those colors are being determined. For now, I think it's fine to go by the driver?

### Breaking Changes  

<!-- - Database schema change (anything that changes DynamoDB document structure)
<!-- - Other change that could cause problems (Detailed in notes)

2021-06-10 01:08 UTC, mg2239 requested changes

2021-06-10 01:08 UTC, mg2239 commented on frontend/src/components/Schedule/Schedule.tsx
> -  };
we dont actually have an easy way to reassign drivers other than drag and drop, so we'll need to include it for now

2021-06-21 12:28 UTC, mly32 commented
I attempted to fix many bugs.

I first checked over the lines with eslint disabled and fixed those (added some useCallbacks)

There were many warnings related to [https://stackoverflow.com/questions/58038008/how-to-stop-memory-leak-in-useeffect-hook-react/58038029
](https://stackoverflow.com/questions/58038008/how-to-stop-memory-leak-in-useeffect-hook-react/58038029
) which was fixed with a check for mount before assignment.

There is still a bug for [https://github.com/anthonyjgrove/react-google-login/issues/311](https://github.com/anthonyjgrove/react-google-login/issues/311) that I attempted to fix by checking if the profile path was defined.

There are some bugs when loading in the rider pages for some reason that I could not resolve.

2021-06-22 00:39 UTC, mg2239 approved these changes
looks really nice, thanks for getting to all the bugs! i made some other style changes and had to revert one of the useCallback fixes you did, since it resulted in editing an employee breaking. its probably doable with useCallback, but i think we can leave it for later.

2021-07-03 16:39 UTC, merged