Met236/prevent weekend rides
cornell-dti/carriage-web pull request #272
Opened 2021-10-21 04:49 UTC by michaeltorku

Used an alert to prevent users from scheduling rides in the carriage frontend on the weekends.

2021-10-26 01:44 UTC, tuckerstanley submitted a review, later dismissed
The code looks very good for the most part. It definitely does the functionality that you were hoping for in not letting the user choose rides on the weekend. My general feedback consists of removing the unnecessary import statements (you dont need import moment in most files now because you deleted that code), and maybe considering using a toast instead of an alert to display the error. This might look better, however check with Matt about that. Making an extra method for Format_date was very smart, and your code looks good.

2021-10-30 16:39 UTC, michaeltorku commented on frontend/src/components/UserDetail/UserDetail.tsx
> +            )} */}
That was there but not by me, I'll delete it

2021-11-07 05:47 UTC, michaeltorku commented
All the changes have been made as requested. Feel free to review again

2021-11-07 19:21 UTC, mg2239 requested changes
really nice work, thanks for making all the changes! added a couple comments, and in case you missed my previous message, the Rider Web ride modal also needs these restrictions too. the code should be pretty much a copy and paste though 👍

2021-11-08 14:21 UTC, mg2239 approved these changes
looks good, great work!

2021-11-08 14:32 UTC, merged