Met236/location context
cornell-dti/carriage-web pull request #288
Opened 2021-11-29 12:12 UTC by michaeltorku

Created a location context file as needed. Integrated the file at multiple points in the code. My integrations made sense to me but would appreciate a critical eye in making sure my changes to existing code were accurate and complete.

2021-12-01 17:12 UTC, mg2239 requested changes
looking pretty good so far, found a few things to fix. you can use `useLocations()` anywhere a GET request to `/locations` is used, so you can put it in the Locations page too.

2021-12-01 17:12 UTC, mg2239 commented on frontend/src/components/RideModal/Pages/RiderInfo.tsx
> +              <option key={l.id}>{l.id}</option>
should be `l.name`, or else this happens
![image](https://user-images.githubusercontent.com/20343975/144279855-a26e6074-75fa-42d9-b542-c5f9d477d015.png)

2021-12-01 17:12 UTC, mg2239 commented on frontend/src/components/RideModal/Pages/RiderInfo.tsx
> +    setLocationToId(locations.map((l) => l.id));
`locationToId` is a map from location name to location id, keep the original code from lines 44 to 48

2021-12-01 17:12 UTC, mg2239 commented on frontend/src/components/RideModal/Pages/RiderInfo.tsx
> +              <option key={l.id}>{l.id}</option>
same here

2021-12-01 17:12 UTC, mg2239 commented on frontend/src/context/LocationsContext.tsx
> +  const componentMounted = useRef(true);
dont need componentMounted, i noticed it doesn't always work and sometimes causes issues

2021-12-01 17:12 UTC, mg2239 commented on frontend/src/context/LocationsContext.tsx
> +    locationsData && componentMounted.current && setLocations(locationsData);
use if blocks

2021-12-01 17:12 UTC, mg2239 commented on frontend/src/components/RideModal/Pages/RiderInfo.tsx
> +  const locations = useLocations().locations;
```suggestion
  const { locations } = useLocations();
```

2021-12-17 19:26 UTC, tuckerstanley reviewed
This code looks well written, you did a good job simplifying the code into the Locations Context module. Not sure if you have addressed Matt's comment regarding the componentMounted yet though.

2021-12-17 19:26 UTC, tuckerstanley commented on frontend/src/components/RideModal/Pages/RiderInfo.tsx
> +    const locationToIdObj = locations.reduce((acc: ObjectType, l) => {
good simplification of the previous method.

2021-12-17 19:26 UTC, tuckerstanley commented on frontend/src/components/RequestRideModal/RequestRideInfo.tsx
> +    setLocations(loc);
good job using useLocations in order to simplify this code.

2021-12-17 19:26 UTC, tuckerstanley commented on frontend/src/context/LocationsContext.tsx
> +        return a.name.toLowerCase() < b.name.toLowerCase() ? -1 : 1;
This is better code than the previous way was. Good work here

2022-01-02 00:39 UTC, mg2239 approved these changes
nice work!

2022-02-18 00:58 UTC, mg2239 approved these changes

2022-02-18 00:59 UTC, merged