jk2375/non-empty-fileBuffer
cornell-dti/carriage-web pull request #289
Opened 2021-12-03 00:22 UTC by justinkang01

### Summary 

Disallow the fileBuffer to be an empty string. Sends a bad request error if fileBuffer happens to be an empty string.

- [x] Implement string checking for fileBuffer

### Test Plan 

### Notes 

### Breaking Changes  

<!-- - Database schema change (anything that changes DynamoDB document structure)
<!-- - Other change that could cause problems (Detailed in notes)

2021-12-05 20:07 UTC, 20austinw approved these changes
Clean code! Looks good to merge.

2021-12-06 04:26 UTC, mg2239 requested changes

2021-12-06 04:26 UTC, mg2239 commented on server/router/upload.ts
> +  }
you actually need an `else` here wrapping the rest of the function, or else the rest of the code will continue to execute

2022-01-10 19:38 UTC, mg2239 approved these changes

2022-01-10 19:40 UTC, merged