Available drivers only allow drivers not already scheduled for a ride
cornell-dti/carriage-web pull request #299
Opened 2022-02-25 01:47 UTC by fengyuli2002

### Summary 

Endpoint `/available` now have a new rule. It filters out drivers who's availability matches the requested ride but are already scheduled for a ride for that time interval.
This is done by scanning the database using dynamoose conditions.

### Test Plan 

### Notes 

Pending testing

### Breaking Changes  

<!-- - Database schema change (anything that changes DynamoDB document structure)
<!-- - Other change that could cause problems (Detailed in notes)

2022-02-27 21:20 UTC, tuckerstanley requested changes
Tried testing this by creating a ride with the drive "Tucker" from 12:11 - 12:15 for TMR, but then I was able to schedule another ride that overlapped with this one with drive "tucker" as well. This would be a bug correct?
<img width="188" alt="Screen Shot 2022-02-27 at 4 17 17 PM" src="https://user-images.githubusercontent.com/25802812/155900289-867bc694-e64c-40de-92ad-e77dacb28592.png">

2022-04-16 22:58 UTC, michaeltorku requested changes
Could you add some comments inside and across this endpoint? I think it looks good functionality wise - but it took a long time to digest so some comments would help with readability: especially in the condition and the logic toward the end

2022-04-19 21:17 UTC, fengyuli2002 commented
> -

2022-04-19 21:23 UTC, fengyuli2002 commented
The parts above which there is no comment belongs to a earlier PR that I made, which was already merged at the beginning of the semester. Those should be correct.

2024-09-20 17:40 UTC, closed without merging