Format edit student modal
cornell-dti/carriage-web pull request #312
Opened 2022-03-20 23:00 UTC by harrisonchin2523

### Summary 

I formatted the edit student modal so that it would match the Figma screen a little more.  
<img width="726" alt="Screen Shot 2022-03-20 at 6 50 35 PM" src="https://user-images.githubusercontent.com/88568615/159189485-06fdcdb4-8469-46b8-a92e-773758dc1451.png">

### Test Plan 

### Notes 

I am a little unsure if I formatted everything the way that we'd want it to be because the textboxes are meant to stay, but they are not present in the Figma. Changes can easily be made in the future if they are not satisfactory though.

2022-03-21 21:27 UTC, fengyuli2002 reviewed
Good job making the modal looks better! A few minor issues that are unclear to me:
1. I didn't find a figma card about Edit Student. I found one about Add Student and it seems you're following that design. Is that the correct design here?
2. In `frontend/src/components/Modal/ridermodal.module.css`, would changing the margin from percentages to `rem` cause inconsistency across different screen sizes?

Appreciate if you can answer these!

2022-03-25 00:21 UTC, harrisonchin2523 commented
> Good job making the modal looks better! A few minor issues that are unclear to me:
> 
> 1. I didn't find a figma card about Edit Student. I found one about Add Student and it seems you're following that design. Is that the correct design here?
> 2. In `frontend/src/components/Modal/ridermodal.module.css`, would changing the margin from percentages to `rem` cause inconsistency across different screen sizes?
> 
> Appreciate if you can answer these!

1. I think the Edit Student card is found in the same row as Add Student in the Figma, but just further right in that row.
2. I think you're right about this and I will look into this.

2022-03-25 00:21 UTC, harrisonchin2523 commented
> Also it seems the `SRLabel` you imported is not used. Any special purposes?

This was something I imported and thought I might use, but I forgot to remove it, I can remove it now.

2022-03-28 17:21 UTC, fengyuli2002 commented
> > Also it seems the `SRLabel` you imported is not used. Any special purposes?
> 
> This was something I imported and thought I might use, but I forgot to remove it, I can remove it now.

Yeah sure!

2022-03-28 17:23 UTC, fengyuli2002 commented
> > Also it seems the `SRLabel` you imported is not used. Any special purposes?
> 
> This was something I imported and thought I might use, but I forgot to remove it, I can remove it now.

Thanks, now I see that. It seems everything is great except the black button is "Save" instead of "Edit student". Good job on the front end!

2022-04-16 22:05 UTC, michaeltorku commented
@harrisonchin2523 I think there's one outstanding requested change - the black button is "Save" instead of "Edit student". Other than that, I think this PR is good to go.

2022-04-16 22:06 UTC, michaeltorku requested changes

2022-04-16 22:06 UTC, michaeltorku commented on frontend/src/components/Modal/RiderModalInfo.tsx
> +          {isEditing ? 'Save' : 'Add a Student'}
'Save' should be 'Edit Student'

2022-04-16 22:29 UTC, RohitValiveti commented
Nice job on the reformatting, Harrison! The changes seem to better resemble the Figma. Just for consistency with the Figma, the "to" between the join and end dates seems to be a bit smaller than the Figma and uncentered. Again, this is a bit knit picky but wanted to address it here for consistency sake. Nice work!
<img width="351" alt="Screen Shot 2022-04-16 at 6 28 31 PM" src="https://user-images.githubusercontent.com/63512824/163693207-4cb7898b-669b-4a78-9a73-c7e9a70dbe31.png">

2022-04-18 01:32 UTC, andrewschoi commented
Nice work Harrison! I think the 'to' should be more centered between the join and end date. Good job!

2023-02-24 01:23 UTC, closed without merging