Minutes asc269
cornell-dti/carriage-web pull request #370
Opened 2022-11-02 23:53 UTC by andrewschoi

When visiting the Employees page on Admin, users can now see driver's availability with minutes

2022-11-09 19:56 UTC, tuckerstanley requested changes
Looking good! See my comments, but these should be quick fixes! Nice job.

2022-11-09 19:56 UTC, tuckerstanley commented on frontend/src/components/EmployeeModal/EmployeeModal.tsx
> +  const { refreshAdmins, refreshDrivers, drivers } = useEmployees();
What do you use drivers for? It doesnt seem like it is used in employeeModal at all.

2022-11-09 19:56 UTC, tuckerstanley commented on frontend/src/components/UserDetail/EmployeeDetail.tsx
> +  console.log(drivers);
Delete! We don't want console.logs getting merged in, they should just be used for testing purposes.

2022-12-09 08:07 UTC, epicdragon44 approved these changes
Looks like all of Tucker's issues were addressed. Approving for merge.

2023-02-04 21:19 UTC, merged