Redesigned the Add/Edit Student Modal
cornell-dti/carriage-web pull request #511
Opened 2024-04-09 06:34 UTC by namanhboi

### Summary 

Changed the styling of the Add/Edit Student Modal to reflect design by Lazim. Changed first and last name fields to just a name field and extracted the first and last name to submit to html form.

The code to extract the first and last name from one name field I took from this [PR#425](https://github.com/cornell-dti/carriage-web/pull/425/) by Desmond.

I still need to redesign the other multiselect needs box and the svg image for the calenders should be gray to reflect Lazim's designs. 

![image](https://github.com/cornell-dti/carriage-web/assets/61220757/69956a26-81dc-4581-a31a-42f3f87cba6e)
_What it looks like_

![image](https://github.com/cornell-dti/carriage-web/assets/61220757/6350536c-66a5-47d9-8073-bce7cfa2e069)
_Here, the correct error for an empty name shows up_

![image](https://github.com/cornell-dti/carriage-web/assets/61220757/ca2f0b86-70c8-4779-9de5-b6954fd1c115)
_Here you can see everything filled in and that I still need to style the multiselect accessibility dropdown_

![image](https://github.com/cornell-dti/carriage-web/assets/61220757/b01d4483-ea19-42c1-81f8-c1a8d70d2a21)
_You can see that the first and last name was extracted correctly. Although I wasn't able to make the request to the server because of a 500._

![image](https://github.com/cornell-dti/carriage-web/assets/61220757/3ad3a57f-5941-4e12-be61-df908433dcd3)
_Here is my error when trying to add a new student to the server_

This pull request is the first step towards redesigning the Add / Edit Student Modal.

### Test Plan 
I tested the design on multiple screensizes and it seems to be working correctly
![image](https://github.com/cornell-dti/carriage-web/assets/61220757/02e4437b-6f3b-49e2-8cc3-1df4b859306e)

For testing the backend, I need to figure out how to connect to the server and finish the multiselect for needs to test everything.

2024-04-14 22:44 UTC, Atikpui007 requested changes
Looks great. You followed the styling to the tea and thats impressive. 
A couple things though 
1. The font color for the labels I suggest you change it to match WCAG guidelines 
- a quick way to check is using this [site](https://webaim.org/resources/contrastchecker/). The ratio should be 4.5+
2. The reason why you are getting the server error when trying to add a student is with the Address. I made a note in an older PR about that #425 
3. Leave the multiselect for the mean time I am working on that PR

2024-04-16 03:03 UTC, raissaji commented
Hey Nam! Like Desmond said, styling looks great! The modal adapts when I shrink the screen size, which is impressive and something I am looking to implement as well.

A few things:

- On my machine, the modal dimensions do not follow Lazim's design. I attached an image below—I'm not sure why this is
<img width="1680" alt="Screenshot 2024-04-15 at 10 54 27 PM" src="https://github.com/cornell-dti/carriage-web/assets/135656237/0a1d522b-8482-492b-959a-c19b03b0c689">

- Desmond said that you're getting a server error because of a conflict with address parsing. I addressed this issue in PR #501 by getting rid of the stringent address requirement entirely. If we merge these two PRs, I believe we should be able to add a student seamlessly

2024-09-24 04:08 UTC, namanhboi commented
Updated color of the fonts in the Add/Edit Student Modal to reflect WCAG guidelines. Address Parsing issue still needs to be addressed in Raissa's [pr](https://github.com/cornell-dti/carriage-web/pull/501). Also CI test is failiing due to timeout issue?

2024-10-17 17:13 UTC, Atikpui007 approved these changes

2024-10-17 18:09 UTC, selenaliu1 approved these changes

2024-10-17 18:10 UTC, merged